apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-svc
  labels:
    app: fraud-detection
spec:
  type: NodePort
  selector:
    app: fraud-detection
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8501
      nodePort: 30080
